<?php

/**
 * @file
 * Sets up HTML5 Tools during install.
 */

variable_set('html5_tools_add_chrome_frame_header', TRUE);
variable_set('html5_tools_override_contact_forms', TRUE);
variable_set('html5_tools_override_doctype', TRUE);
variable_set('html5_tools_override_meta_tags', TRUE);
variable_set('html5_tools_override_script_tags', TRUE);
variable_set('html5_tools_override_search_block_form', TRUE);
variable_set('html5_tools_override_search_form', TRUE);
variable_set('html5_tools_override_style_tags', TRUE);
variable_set('html5_tools_override_submitted', TRUE);
variable_set('html5_tools_override_system_site_information_form', TRUE);
variable_set('html5_tools_override_user_register_form', TRUE);
variable_set('html5_tools_override_views_field_rewrite_elements', TRUE);
