<?php

/**
 * @file
 * Sets up External Links during install.
 */

variable_set('extlink_alert_text', 'This link will take you to an external web site. We are not responsible for their content.');
variable_set('extlink_class', 'ext');
variable_set('extlink_exclude', '');
variable_set('extlink_include', '');
variable_set('extlink_mailto_class', 'mailto');
variable_set('extlink_subdomains', 1);
variable_set('extlink_target', '_blank');
