<?php

/**
 * @file
 * Sets up Path Breadcrumbs during install.
 */

variable_set('path_breadcrumbs_decode_entities', TRUE);
variable_set('path_breadcrumbs_delimiter', '»');
variable_set('path_breadcrumbs_hide_single_breadcrumb', FALSE);
variable_set('path_breadcrumbs_home_link_enabled', TRUE);
variable_set('path_breadcrumbs_home_link_title', 'Home');
variable_set('path_breadcrumbs_internal_render', FALSE);
variable_set('path_breadcrumbs_rich_snippets', '0');
