<?php

/**
 * @file
 * Sets up Colorbox during install.
 */

variable_set('colorbox_caption_trim', '0');
variable_set('colorbox_caption_trim_length', '75');
variable_set('colorbox_compression_type', 'minified');
variable_set('colorbox_custom_settings_activate', '0');
variable_set('colorbox_fixed', TRUE);
variable_set('colorbox_initialheight', '250');
variable_set('colorbox_initialwidth', '300');
variable_set('colorbox_inline', FALSE);
variable_set('colorbox_load', TRUE);
variable_set('colorbox_maxheight', '98%');
variable_set('colorbox_maxwidth', '98%');
variable_set('colorbox_opacity', '0.85');
variable_set('colorbox_overlayclose', TRUE);
variable_set('colorbox_pages', 'admin*
imagebrowser*
img_assist*
imce*
node/add/*
node/*/edit
print/*
printpdf/*
system/ajax
system/ajax/*');
variable_set('colorbox_scrolling', '1');
variable_set('colorbox_slideshow', '0');
variable_set('colorbox_slideshowauto', TRUE);
variable_set('colorbox_slideshowspeed', '2500');
variable_set('colorbox_style', 'profiles/openfed/libraries/colorbox/example4');
variable_set('colorbox_text_close', 'Close');
variable_set('colorbox_text_current', '{current} of {total}');
variable_set('colorbox_text_next', 'Next »');
variable_set('colorbox_text_previous', '« Prev');
variable_set('colorbox_text_start', 'start slideshow');
variable_set('colorbox_text_stop', 'stop slideshow');
variable_set('colorbox_transition_speed', '350');
variable_set('colorbox_transition_type', 'elastic');
variable_set('colorbox_visibility', '0');
