<?php

/**
 * @file
 * Sets up Pathauto during install.
 */

variable_set('pathauto_blog_pattern', 'blogs/[user:name]');
variable_set('pathauto_case', 1);
variable_set('pathauto_forum_pattern', '[term:vocabulary]/[term:name]');
variable_set('pathauto_ignore_words', 'a, an, as, at, before, but, by, for, from, is, in, into, like, of, off, on, onto, per, since, than, the, this, that, to, up, via, with');
variable_set('pathauto_max_component_length', 100);
variable_set('pathauto_max_length', 100);
variable_set('pathauto_node_pattern', 'content/[node:title]');
variable_set('pathauto_punctuation_ampersand', 0);
variable_set('pathauto_punctuation_asterisk', 0);
variable_set('pathauto_punctuation_at', 0);
variable_set('pathauto_punctuation_backtick', 0);
variable_set('pathauto_punctuation_back_slash', 0);
variable_set('pathauto_punctuation_caret', 0);
variable_set('pathauto_punctuation_colon', 0);
variable_set('pathauto_punctuation_comma', 0);
variable_set('pathauto_punctuation_dollar', 0);
variable_set('pathauto_punctuation_double_quotes', 0);
variable_set('pathauto_punctuation_equal', 0);
variable_set('pathauto_punctuation_exclamation', 0);
variable_set('pathauto_punctuation_greater_than', 0);
variable_set('pathauto_punctuation_hash', 0);
variable_set('pathauto_punctuation_hyphen', 1);
variable_set('pathauto_punctuation_left_curly', 0);
variable_set('pathauto_punctuation_left_parenthesis', 0);
variable_set('pathauto_punctuation_left_square', 0);
variable_set('pathauto_punctuation_less_than', 0);
variable_set('pathauto_punctuation_percent', 0);
variable_set('pathauto_punctuation_period', 0);
variable_set('pathauto_punctuation_pipe', 0);
variable_set('pathauto_punctuation_plus', 0);
variable_set('pathauto_punctuation_question_mark', 0);
variable_set('pathauto_punctuation_quotes', 0);
variable_set('pathauto_punctuation_right_curly', 0);
variable_set('pathauto_punctuation_right_parenthesis', 0);
variable_set('pathauto_punctuation_right_square', 0);
variable_set('pathauto_punctuation_semicolon', 0);
variable_set('pathauto_punctuation_slash', 0);
variable_set('pathauto_punctuation_tilde', 0);
variable_set('pathauto_punctuation_underscore', 0);
variable_set('pathauto_reduce_ascii', TRUE);
variable_set('pathauto_separator', '-');
variable_set('pathauto_taxonomy_term_pattern', '[term:vocabulary]/[term:name]');
variable_set('pathauto_transliterate', TRUE);
variable_set('pathauto_update_action', 2);
variable_set('pathauto_user_pattern', 'users/[user:name]');
variable_set('pathauto_verbose', FALSE);
